---
dma: "longdma"
labjack : 470024266
labjack_io :
  "flow_read_input": "AIN0"
  "voltage_monitor_input": "AIN5"
  "press_input": "AIN2"
  "temp_input": "AIN3"
  "rh_input": "AIN4"
  "voltage_set_output": "TDAC4"
  "flow_set_output": "TDAC2"
  "counter": "DIO18"
  "width": "DIO0"
cpc_config:
  "cpc_flowrate" : 16.6667 # 300/60 cubic centimeters per second
voltage_set_config:
  "voltage_set_factor" : 1857.527 # 10000/5 (supply range)/5 (includes calibration between set V and multimeter readout)
  "voltage_offset_calibration" : 0.004585 
  "dma_outer_radius" : 1.92659
  "dma_inner_radius" : 0.94266
  "dma_length" : 44.348
sensor_config:
  "temp_factor" : 0.01
  "flow_factor" : 5.8343
  "flow_offset" : 0.9947
  "voltage_factor" : 894.2144
  "voltage_offset" : 0.011578
  "polynom_offset" : -39.981
gui_config:
  "low_dia_lim" : 10
  "high_dia_lim" : 600  
  "bins" : 50  # Number of steps in voltage cycle
  "voltage_update_time" : 5000  # Time between each voltage step
  "blower_flow_set" : 15 # LPM
  "diameter_list" : [241.614,269.325,300.963,337.176,378.691,426.428,481.080,141.400,244.900,346.400,447.200,591.600,836.700,1414.000,4472.000]
  "default_mode" : "dia_list"
pid_config:
  "pidp" : 0.2
  "pidi" : 0
  "pidd" : 0