---
dma: "longdma"
start_interval: 5
threads:
  "blower" : True
  "voltage_scan" : True
  "voltage_monitor" : True
  "datalogging" : True
  "cpc_counting" : True
  "cpc_serial" : True
  "cpc_fill" : False
keys:
  "blower" : ["blower thread time","temp","rh","press","flow","blower runtime"]
  "voltage_scan" : ["volt set thread time","volt set","dia set","volt set runtime"]
  "voltage_monitor" : ["volt monitor thread time","supply_volt","volt monitor runtime"]
  "cpc_counting" : ["cpc count thread time","concentration","count","pulse width","pulse width error","concentration no-deadtime","cpc count runtime"]
  "cpc_serial" : ["cpc serial thread time", "concentration","instrument errors","saturator temp","condensor temp","optics temp", "cabinet temp","ambient pressure","orifice pressure","nozzle pressure","laser current","liquid level","aersol flow", "inlet flow","serial number","corrected counts","uncorrected counts","serial runtime"]
data_config:
  "header": ["Datetime","Count","Elapsed Time","Scan Start Time","Calculated Diameter [nm]","dNdlnDp"]
  "serial_commands": ["RALL", "RSF", "RIF","RSN","RCOUNT1","RCOUNT2"]
  "serial_port": "COM8"
  "serial_baud": 115200
  "serial_bytesize": 8
  "serial_parity": "N"
  "serial_timeout": 0.05
  "start_commands" : []
  "fill_index": 0
labjack : 470024266
labjack_io :
  "flow_read_input": "AIN0"
  "voltage_monitor_input": "AIN5"
  "press_input": "AIN2"
  "temp_input": "AIN3"
  "rh_input": "AIN4"
  "voltage_set_output_pos": "TDAC4"
  "voltage_set_output_neg": "TDAC5"
  "flow_set_output": "TDAC2"
  "counter": "DIO18"
  "width": "DIO0"
  "fill_valve" : "nan"
cpc_config:
  "cpc_flowrate" : 16.6667 # 300/60 cubic centimeters per second
voltage_set_config:
  "voltage_set_factor" : 2001 #1857.527 # 10000/5 (supply range)/5 (includes calibration between set V and multimeter readout)
  "voltage_offset_calibration" : 0.00244802921 #0.004585 
  "dma_outer_radius" : 1.92659 # Mark's DMAdim sheet
  "dma_inner_radius" : 0.94266 # Mark's DMAdim sheet
  "dma_length" : 44.348 # Mark's DMAdim sheet
  "dma_eff_length": 13 # Reineking and Porstendorfer 1986 [m]
  "dma_sample_flow" : 1000 #[sccm]
  "aerosol_charge" : -1 # [-1 for negative, 1 for positive]
  "dlnDp_old" : 0.062173 
  "dlnDp" : 0.114195
sensor_config:
  "temp_factor" : 0.01
  "flow_factor" : 5.8343
  "flow_offset" : 0.9947
  "flow_start" : 2
  "voltage_factor" : 2017.8 #2000*1.0089
  "voltage_offset" : -0.014157 # 29.93/2017.8
gui_config:
  "low_dia_lim" : 10
  "high_dia_lim" : 350 
  "bins" : 50  # Number of steps in voltage cycle
  "voltage_update_time" : 10000  # Time between each voltage step
  "blower_flow_set" : 10 # LPM
  "diameter_list_old" : [1.00001,9.506,10.116,10.764,11.455,12.190,12.972,13.804,14.689,15.631,16.634,17.701,18.837,20.045,21.331,22.699,24.155,25.705,27.353,29.108,30.975,32.962,35.077,37.327,39.721,42.269,44.980,47.866,50.936,54.203,57.680,61.380,65.318,69.508,73.966,78.711,83.760,89.133,94.850,100.935,107.409,114.299,121.631,129.433,137.736,146.571,155.973,165.978,176.625,187.955,200.012,212.842,226.495,241.024,256.484,272.937,290.445,309.076,328.902,350.000]
  "diameter_list" : [1.00001,14.303,16.033,17.973,20.147,22.584,25.316,28.379,31.812,35.660,39.974,44.809,50.230,56.306,63.118,70.753,79.312,88.907,99.662,111.718,125.233,140.383,157.365,176.401,197.741,221.662,248.476,278.535,312.229,350.000]
  "default_mode" : "dia_list"
  "contour_min" : 10
  "contour_max" : 1000
  "y_min" : 8
  "y_max" : 500
  "scan_polarity": "positive"
pid_config:
  "pidp" : 0.05
  "pidi" : 0.005
  "pidd" : 0