---
dma: "test"
start_interval: 1
threads:
  "blower" : True
  "voltage_scan" : True
  "voltage_monitor" : True
  "datalogging" : True
  "cpc_counting" : True
  "cpc_serial" : False
  "cpc_fill" : False
keys:
  "blower" : ["blower thread time","temp","rh","press","flow","blower runtime"]
  "voltage_scan" : ["volt set thread time","volt set","dia set","volt set runtime"]
  "voltage_monitor" : ["volt monitor thread time","supply_volt","volt monitor runtime"]
  "cpc_counting" : ["cpc count thread time","concentration","count","pulse width","pulse width error","concentration no-deadtime","cpc count runtime"]
  "cpc_serial" : ['time','concentration','condensor temp','saturator temp','optics temp','flow','ready environment','reference detector voltage','detector voltage','pump control value','1 second counts','liquid level']
data_config:
  "header": ["Datetime","Count","Elapsed Time","Calculated Diameter [nm]","dNdlnDp","Set Voltage [V]","Set Diameter [nm]","Actual Voltage [V]","Flow Rate [LPM]","Temperature [C]","RH [%]","Pressure [kPa]","Concentration [#/cc]","Concentration No Deadtime[#/cc]","Counts [#]","Pulse Width [s]","Pulse Width Error [%]","Blower Control Runtime [s]","Voltage Update Runtime [s]","Voltage Monitor Runtime [s]","CPC Counting Runtime [s]","Datalogging Runtime[s]"]
  "serial_commands": ['RD','R1','R2','R3','R4','R5','R6','R7','RE','RB','R0']
  "cpc_header" :  ['time','concentration','condensor temp','saturator temp','optics temp','flow','ready environment','reference detector voltage','detector voltage','pump control value','1 second counts','liquid level']
  "serial_port": "COM6"
  "serial_baud": 9600
  "serial_bytesize": 7
  "serial_parity": "E"
  "serial_timeout": 0.05
  "start_commands" : []
  "fill_index": 10
labjack : "ANY"
labjack_io :
  "flow_read_input": "AIN0"
  "voltage_monitor_input": "AIN1"
  "press_input": "AIN2"
  "temp_input": "AIN3"
  "rh_input": "AIN4"
  "voltage_set_output_pos": "DAC0"
  "voltage_set_output_neg": "DAC0"
  "flow_set_output": "DAC1"
  "counter": "DIO18"
  "width": "DIO0"
  "fill_valve" : "DIO3"
cpc_config:
  "cpc_flowrate" : 16.6667 # 300/60 cubic centimeters per second
voltage_set_config:
  "voltage_set_factor" : 2000 # 10000/5 (supply range)/5
  "voltage_offset_calibration" : 0.004585 
  "dma_outer_radius" : 1.92659
  "dma_inner_radius" : 0.94266
  "dma_length" : 44.348
  "dma_eff_length": 13 # [m]
  "dma_sample_flow" : 1800 #[sccm]
  "aerosol_charge" : -1 # [-1 for negative, 1 for positive]
  "dlnDp" : 0.1243460
  "dlnDp" : 0.114195
sensor_config:
  "temp_factor" : 0.01
  "flow_factor" : 5.8343
  "flow_offset" : 0.9947
  "voltage_factor" : 894.2144
  "voltage_offset" : 0.011578
gui_config:
  "low_dia_lim" : 1
  "high_dia_lim" : 600  
  "bins" : 3  # Number of steps in voltage cycle
  "voltage_update_time" : 2000  # Time between each voltage step
  "blower_flow_set" : 15 # LPM
  "diameter_list" : [2.798,3.048,3.320,3.616,3.938,4.289,4.671,5.088,5.543,6.038,6.578,7.166,7.808,8.507,9.270,10.103,11.011,12.002,13.083,14.264,15.553,16.960,18.499,20.180,22.017,24.027,26.227,28.635,31.271,34.141,29.933,32.517,35.328,38.391,41.741,45.402,49.409,53.797,58.610,63.896,69.709,76.108,83.172,90.981,99.623,109.225,119.907,131.819,145.134,160.063,176.857,195.823,217.269,241.614,269.325,300.963,337.176,378.691,426.428,481.080,141.400,244.900,346.400,447.200,591.600,836.700,1414.000,4472.000]
  "default_mode" : "dia_list"
  "contour_min" : 0.0001
  "contour_max" : 10
  "y_min" : 1
  "y_max" : 500
  "scan_polarity": "positive"
pid_config:
  "pidp" : 0.2
  "pidi" : 0
  "pidd" : 0